name: KiPlot

on:
  push:
    paths:
      - '**.pro'
      - '**.sch'
      - '**.kicad_pcb'
      - '**.lib'
      - '**/greenpill.pretty/*'
  pull_request:
    paths:
      - '**.pro'
      - '**.sch'
      - '**.kicad_pcb'
      - '**.lib'
      - '**/greenpill.pretty/*'

jobs:
  pdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pdf2svg
      run: sudo apt-get install -y pdf2svg
    - name: Make docs dir
      run: "mkdir -p docs/"
    - uses: nerdyscout/kicad-exports@v2.0
      with:
      # Required - kiplot config file
        config: config.kiplot.yaml
      # optional - prefix to output defined in config
        dir: 'docs/'
      # optional - schematic file
        schema: '1.0/greenpill.sch'
      # optional - PCB design file
        board: '1.0/greenpill.kicad_pcb'
    - name: ls
      run: "ls -la docs/"
    - name: Convert schematic PDFs to SVG
      run: pdf2svg docs/greenpill-schematic.pdf docs/greenpill-schematic.svg 
      # only use the first page - we need to change this if heirarchial sheets are added.
    - name: upload schematic
      uses: actions/upload-artifact@v2
      with:
        name: Schematic and board PDFs
        path: docs/
        if-no-files-found: error
    - name: Commit docs/
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/greenpill-schematic.pdf docs/greenpill-board.pdf docs/greenpill-schematic.svg
        git commit -m "Updated auto-generated files in docs/"
        git push